// support-desk-react/src/components/footer/Footer.jsx
import React from 'react';
import { Toolbar, Typography, Box } from '@mui/material';
import './Footer.scss';

function Footer() {
const credits = '{{ MonaCodeLisa }}';

  return (
    <Box className="footer">
        <Toolbar>
          <Typography>
            <a href="https://www.linkedin.com/in/monacodelisa/" target="_blank" rel="noreferrer">{credits}</a>
          </Typography>
        </Toolbar>
    </Box>
  );
}

export default Footer;

// support-desk-angular/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

  credits = '{{MonaCodeLisa}}'
}

<a href="https://www.linkedin.com/in/monacodelisa/" target="=_blank">{{ credits }}</a>
