// support-desk-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'support-desk-angular';
}

<app-header></app-header>
<app-people></app-people>
<app-footer></app-footer>

// support-desk-react/src/App.jsx
// import logo from './logo.svg';
import Header from './components/header/Header'
import People from './components/people/People'
import Footer from './components/footer/Footer'
import './App.scss';

function App() {
  return (
    <div className="App">
      <Header />
      <main>
        <People />
      </main>
      <Footer />
    </div>
  );
}

export default App;
